#!/bin/bash -e
export VERSION_NAME="$(lsb_release -sc)"
wget https://repo.percona.com/apt/percona-release_latest."${VERSION_NAME}"_all.deb
sudo dpkg -i percona-release_latest."${VERSION_NAME}"_all.deb
sudo apt-get -f -y install
sudo /usr/bin/percona-release enable-only tools
sudo apt update
