#!/bin/bash -ex
[ -n "$1" ] || { echo "must pass mysql version"; exit 1; }
MYSQL_PACKAGE_VERSION="$1"
export DEBIAN_FRONTEND="noninteractive"

sudo debconf-set-selections <<< 'mysql-community-server mysql-community-server/re-root-pass password ROOTPASSWORD'
sudo debconf-set-selections <<< 'mysql-community-server mysql-community-server/root-pass password ROOTPASSWORD'
sudo debconf-set-selections <<< 'mysql-community-server mysql-server/default-auth-override select Use Strong Password Encryption (RECOMMENDED)'

rm -f mysql-*.deb

VENDOR="$(dpkg-vendor --query Vendor)"
if [[ "${VENDOR}" = Ubuntu ]]; then
    DIST="ubuntu"
    VERSION_ID=$"$(lsb_release -r -s)"
elif [[ "${VENDOR}" = "Debian" ]]; then
    DIST="debian"
    VERSION_ID=$"$(lsb_release -r -s)"
    if [[ "${VERSION_ID}" = "n/a" ]]; then
        # Fall back to latest stable version on sid/testing
        VERSION_ID="$(distro-info -r --stable)"
    fi
else
    echo "Unknown vendor ${VENDOR}"
    exit 1
fi

export mysql_debs=(
mysql-community-client-plugins_${MYSQL_PACKAGE_VERSION}-1${DIST}${VERSION_ID}_amd64.deb
mysql-common_${MYSQL_PACKAGE_VERSION}-1${DIST}${VERSION_ID}_amd64.deb
mysql-community-client-core_${MYSQL_PACKAGE_VERSION}-1${DIST}${VERSION_ID}_amd64.deb
mysql-community-client_${MYSQL_PACKAGE_VERSION}-1${DIST}${VERSION_ID}_amd64.deb
mysql-client_${MYSQL_PACKAGE_VERSION}-1${DIST}${VERSION_ID}_amd64.deb
mysql-community-server-core_${MYSQL_PACKAGE_VERSION}-1${DIST}${VERSION_ID}_amd64.deb
mysql-community-server_${MYSQL_PACKAGE_VERSION}-1${DIST}${VERSION_ID}_amd64.deb
mysql-server_${MYSQL_PACKAGE_VERSION}-1${DIST}${VERSION_ID}_amd64.deb
)

for package in "${mysql_debs[@]}"; do wget "https://repo.mysql.com/apt/${DIST}/pool/mysql-8.0/m/mysql-community/${package}"; done
set +e
for package in "${mysql_debs[@]}"; do sudo dpkg -i "$package" ; done
set -e
sudo apt-get -f -y install
