#!/bin/bash -e
[ -n "$1" ] || { echo "must pass percona package version"; exit 1; }
PERCONA_PACKAGE_VERSION="$1"
export DEBIAN_FRONTEND="noninteractive"
sudo apt-get install -q -y --allow-unauthenticated -o Dpkg::Options::=--force-confnew percona-xtrabackup-80="${PERCONA_PACKAGE_VERSION}"
mysqld --version
