#!/bin/bash -e
[ -n "$1" ] || { echo "must pass python version"; exit 1; }
PYTHON_VERSION="$1"
export DEBIAN_FRONTEND="noninteractive"
apt-get update
apt-get -y install python${PYTHON_VERSION}-full
python${PYTHON_VERSION} -m ensurepip


