#!/bin/bash -e
[ -r "/etc/PYTHON_VERSION" ] && [ -z "${PYTHON_VERSION}" ] && { source /etc/PYTHON_VERSION ; }
[ -z "${PYTHON_VERSION}" ] && { echo "must define PYTHON_VERSION"; exit 1; }
python${PYTHON_VERSION} -m pip install -r requirements.txt
python${PYTHON_VERSION} -m pip install -r requirements.dev.txt
python${PYTHON_VERSION} -m pip install -e .
