#!/bin/bash -e
export DEBIAN_FRONTEND="noninteractive"
sudo debconf-set-selections <<< 'mysql-community-server	mysql-community-server/remove-data-dir	boolean	true'
sudo apt purge -y mysql-server mysql-client mysql-common mysql-server-core-* mysql-client-core-* || echo "MySQL was not installed; proceeding."
sudo rm -rf /var/lib/mysql
