#!/bin/bash -e
# this is designed to be launched INSIDE the container to install deps
[ -n "${PYTHON_VERSION}" ] || { echo "outside env must define PYTHON_VERSION"; exit 1; }
[ -n "${MYSQL_VERSION}" ] || { echo "outside env must define MYSQL_VERSION"; exit 1; }
[ -n "${PERCONA_VERSION}" ] || { echo "outside env must define PERCONA_VERSION"; exit 1; }
mkdir /testdir
cd /testdir
rsync -a /src .
cd src
make -e install-ubuntu
