#!/bin/bash -e
# this is designed to be launched INSIDE the container to run tests
[ -n "${PYTHON_VERSION}" ] || { echo "outside env must define PYTHON_VERSION"; exit 1; }
cd /testdir
rsync -a /src .
chown -R testme:testme src
cd src
su - testme make PYTHON="python${PYTHON_VERSION}" coverage
